config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :instructors
    resources :clients
    root to: "instructors#welcome"

    get '/instructor', to: 'instructors#show'
    get '/custom_query', to: 'clients#custom_query'
    get 'clients/:id/next', to: 'clients#next'
    #get 'clients/:id/client_data', to: 'clients#client_data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :instructor 
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end 

app/controllers/client_controller.rb
class ClientController < ApplicationController

  before_action :set_client, only: [:show, :edit, :update]

  def index
    @client = Client.all
    render json: @client, status: 200
  end

  def show
    @client = Client.find(params[:id])
    render json: @client, status: 200
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)
    @client.save
    render json: @client, status: 201
  end

  def edit
  end

  def update
    @client.update(client_params)
    render json: @client, status: 202
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :age, :goals)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destory]

  def index
    @client = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)
      if @client.save
        redirect_to @client, notice: 'Client was successfully created.'
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

private
  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:id, :name, :age, :goals)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  def index
    @instructor = Instructor.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @instructor}
    end
  end

  def show
    @instructor = Instructor.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @instructor}
    end
  end

  def new
    @instructor = Instructor.new
  end

  def edit
  end

  def create
    @instructor = Instructor.new(instructor_params)
    @instructor.save
      render json: @instructor 
  end

  def update
    if @instructor.update(instructor_params)
      respond_to do |f|
        f.html {redirect_to @instructor, notice: 'Instructor was successfully updated.'}
        f.json {render json: @instructor}
      end
    else
      render :edit
    end
  end


  def destroy
    @instructor.destroy
    respond_to do |f|
      f.html {redirect_to instructors_url, notice: 'Instructor was successfully destroyed.'}
      f.json {head :no_content}
    end
  end

  private

    def set_instructor
      @instructor = Instructor.find_by_id(params[:id])
    end

    def instructor_params
      params.require(:instructor).permit(:name, :bio, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :goals %>
    <%= form.text_field :goals %>
  </div>

  <div class="field">
    <%= form.label :instructor_id %>
    <%= form.text_field :instructor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Goals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.age %></td>
        <td><%= client.goals %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="our-new-clients"></div>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

  <strong>Name:</strong>
  <%= @client.name %>
  <strong>Age:</strong>
  <%= @client.age%>
  <strong>Goals:</strong>
  <%= @client.goals%>

<%= link_to 'Edit', edit_client_path(@client) %>
<%= link_to 'Back', client_path %>

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true, html: {id: "new_instructor"}) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio %>
  </div>

  <button id="submit-me">Create Instructor</button>
  <div id="create-instructors"></div>

<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructor.each do |instructor| %>
      <tr>
        <td><%= link_to instructor.name, instructors_path %></td>
        <td><%= instructor.bio %></td>
        <td><%= link_to 'Delete', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Client', new_client_path %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="our-new-instructors"></div>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
  <h2>Name:</h2>
  <%= @instructor.name %>
  <h3>Bio:</h3>
  <%= @instructor.bio%>
  <h4>Clients:</h4>
  <%= @instructor.clients.name%>

<div>
<%= link_to 'Back', instructors_path %>
</div>

app/views/instructors/welcome.html.erb
<h1>Welcome to GymTime!</h1>

app/views/layouts/_nav.html.erb
<div class='topnav'>
      <%=link_to "Home", root_path%>
      <%= link_to "Instructors", instructors_path, class:"all_instructors"%>
      <%= link_to "New Instructor", new_instructor_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymtimeJs</title>
    <%= render 'layouts/nav' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <div class= "container">
      <% render 'layouts/nav' %>
      <div id="app-container">
        <%= yield %>
      </div>
    </div>    
  </body>
</html>